import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/client.ts',
    'src/modules/user/index.ts',
    'src/modules/department/index.ts',
    'src/modules/tag/index.ts',
    'src/modules/batch/index.ts',
    'src/modules/agent/index.ts',
    'src/modules/agent-menu/index.ts',
    'src/modules/media/index.ts',
    'src/modules/message/index.ts',
    'src/modules/app-chat/index.ts',
    'src/modules/external-contact/index.ts',
    'src/modules/calendar/index.ts',
    'src/modules/schedule/index.ts',
    'src/modules/meeting-room/index.ts',
    'src/modules/checkin/index.ts',
    'src/modules/approval/index.ts',
    'src/modules/dial/index.ts',
    'src/modules/invoice/index.ts',
    'src/modules/callback/index.ts',
    'src/modules/suite/index.ts',
    'src/modules/provider/index.ts',
    'src/modules/webhook/index.ts',
    'src/modules/aibot/index.ts',
    'src/modules/hardware/index.ts',
  ],
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  target: 'node22.18',
  platform: 'node',
});
